import { getDefaultAwsClients as aws } from './aws-clients';
import { ComponentRequest, ResourceNotFoundException } from '@aws-sdk/client-iottwinmaker';

// TODO create types file
type EntityDefinitionForSync = {
  entityId: string | { lookupByPath: string } | undefined;
  entityName: string | undefined;
  description?: string | undefined;
  components?: { [key: string]: ComponentRequest } | undefined;
  parentEntityId?: string | undefined;
  tags?: { [key: string]: string } | undefined;
  autoGeneratedEntityId?: string;
  isProcessed?: boolean | undefined;
};

/**
 * Helper function to wait for set amount of time
 * @param ms number of ms to wait
 */
async function delay(ms: number) {
  await new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

/**
 * Helper function during workspace nuke for determining existance of workspace
 * @param workspaceId TM workspace
 * @returns promise boolean
 */
async function verifyWorkspaceExists(workspaceId: string) {
  try {
    await aws().tm.getWorkspace({ workspaceId: workspaceId });
  } catch (e) {
    if (e instanceof ResourceNotFoundException) {
      console.error(`Error: workspace '${workspaceId}' not found. Please create it first.`);
      throw e;
    } else {
      console.error(`Failed to get workspace.`, e);
      throw e;
    }
  }
  console.log(`Verified workspace ${workspaceId} exists.`);
}

export { delay, verifyWorkspaceExists };
export type { EntityDefinitionForSync };
